### ISSUE TITLE
[BUG]CUDA out of memory

### ISSUE THREAD

**Issue by genbei** [TharinduDR/TransQuest#26]
git clone https://github.com/TharinduDR/TransQuest.git
cd TransQuest
pip install -r requirements.txt

when i run `python -m examples.sentence_level.wmt_2020_task2.en_zh.siamesetransquest`

 I think you should modify your code. Because of the following problems,I made the same mistake by reducing batch_size to 4. Maybe you should `torch.cuda.empty_cache ()`, or `with torch.no_grad()`

> Traceback (most recent call last):
File "/home/miniconda3/envs/transquest/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/home/miniconda3/envs/transquest/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/TransQuest-master/examples/sentence_level/wmt_2020_task2/en_zh/siamesetransquest.py", line 67, in
model.train_model(train_df, eval_df)
File "/home/TransQuest-master/transquest/algo/sentence_level/siamesetransquest/run_model.py", line 98, in train_model
output_path=self.args.best_model_dir)
File "/home/TransQuest-master/transquest/algo/sentence_level/siamesetransquest/models.py", line 693, in fit
loss_value.backward()
File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
File "/home/miniconda3/envs/transquest/lib/python3.7/site-packages/torch/autograd/init.py", line 147, in backward
allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 978.00 MiB (GPU 0; 14.73 GiB total capacity; 10.25 GiB already allocated; 625.88 MiB free; 13.21 GiB reserved in total by PyTorch)

**Comment by TharinduDR** [comment]
Where would you suggest to add `torch.cuda.empty_cache ()`, or `with torch.no_grad()`?

**Comment by genbei** [comment]
> Where would you suggest to add `torch.cuda.empty_cache ()`, or `with torch.no_grad()`?

I didn't come and modify the code. I just lowered batchsize to 2. won't you have this problem when you run?

**Comment by TharinduDR** [comment]
If the code works when you reduce the batch size, it means that there no bug in the code. It is just you need a better GPU. I have been running the code in a Nvidia P100, and it works fine
